# Generated by Django 3.2.7 on 2022-04-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='archivo_registro',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
