# Generated by Django 3.2.7 on 2022-04-24 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_csv', '0002_registro_archivo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
